### ISSUE TITLE
/contactdb/recipients ... a valid endpoint?

### ISSUE THREAD

**Issue by wyattisimo** [awwa/sendgrid4r#1]
None of the methods in the `Recipients` module seem to work. It always comes back with a 404. Also, I can't find anything in SendGrid's documentation about this `/contactdb/recipients` endpoint. Where did you get that from?

**Comment by awwa** [comment]
I also get 404.
The contacts API is currently under BETA.
So it seems the documentation is not fixed.
I think you can access the documentation Early Access: Marketing Campaign.
