### ISSUE TITLE
sendgrid4r-1.1.0/lib/client.rb:18: duplicated argument name (SyntaxError)

### ISSUE THREAD

**Issue by raulsann** [awwa/sendgrid4r#10]
I keep getting this error when the app starts:

    /gems/sendgrid4r-1.1.0/lib/client.rb:18: duplicated argument name (SyntaxError)

any idea why this is happening?

Thanks !

**Comment by awwa** [comment]
How have you created a client instance?
Could you confirm the documentation?
https://github.com/awwa/sendgrid4r/wiki/Create-A-Client-Instance

**Comment by raulsann** [comment]
Hi @awwa, this is how i have created it sendgrid.rb:

    SendgridNewsletter = GatlingGun.new(ENV['SENDGRID_USERNAME'], ENV['SENDGRID_PASSWORD'])
    
    SendgridClient = SendGrid::Client.new(api_user: ENV['SENDGRID_USERNAME'], api_key: ENV['SENDGRID_PASSWORD'])
    
    # Sendgrid4rClient = Sendgrid4r::Client.new(username: ENV['SENDGRID_USERNAME'], password: ENV['SENDGRID_PASSWORD'])

the latest line is commented because I had to remove sendgrid4r to avoid having this error. My gemfile looks like this: 


    # gem 'sendgrid4r', '1.1.0'
    gem "gatling_gun"
    gem "sendgrid-ruby"


as soon as I uncomment the line:

    gem 'sendgrid4r', '1.1.0'

I get the error. Thank you for your reply!

**Comment by awwa** [comment]
SendGrid4r hasn't the class name 'Sendgrid4r'.
Could you try SendGrid4r::Client.new()?

**Comment by raulsann** [comment]
That worked. I copied it from an example but I can't remember where the example was....

Thank you Awwa.

**Comment by raulsann** [comment]
Found it! This page needs to be corrected: https://github.com/awwa/sendgrid4r/wiki/Create-A-Client-Instance

**Comment by awwa** [comment]
Thanks for your feedback!!
I have fixed the [wrong example](https://github.com/awwa/sendgrid4r/wiki/Create-A-Client-Instance).
