### ISSUE TITLE
Using templates and actionmailer to send emails through smtp

### ISSUE THREAD

**Issue by mklemme** [awwa/sendgrid4r#20]
I'm using the template engine to send the transactional email. Template creation and version creation are working using the api. When I call deliver_now, the mailer uses the content in my view, not the Sendgrid template.

When I remove the template_name & template_path, it throws a missing template error.

What extra config do I need to do so it uses the Sendgrid template instead of my local version?

XX_mailer.rb:
```
headers "X-SMTPAPI" => {
  category: ["newsletter", "newsletter-#{ref_id}"],
  unique_args: {
    ref: "CO-NEW-#{ref_id}",
    newsletter_id: ref_id
  },
  filters: {
    templates: {
      settings: {
        enable: 1,
        template_id: template
      }
    }
  },
  sub: {
    "%token%" => token_values,
    "%email%" => emails
  },
  section: {
    "%unsubscribeText%" => "Unsubscribe from our digests"
  }
}.to_json

mail(
  from: 'dobby@hogwarts.com',
  subject: subject,
  template_path: 'email/content',
  template_name: story_format
)
```

**Comment by awwa** [comment]
I believe you can send the email with your template if you set the correct template id via X-SMTPAPI. 
This gem is able to create the templates and versions. But it does not support send email API. So I can not answer about your question. [The SendGrid documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/smtpapi.html) may be helpful for you.
