### ISSUE TITLE
domain does not seem to be a valid argument for patch

### ISSUE THREAD

**Issue by chalmagean** [awwa/sendgrid4r#29]
This is a followup of: https://github.com/awwa/sendgrid4r/issues/28

The issue is not fixed.

```
sc.patch_wl_domain(id: 440089, domain: 'test.com', subdomain: 'email')
ArgumentError: unknown keywords: domain, subdomain
```

P.S. I don't see the ability to update the domain or subdomain in the docs:
https://sendgrid.com/docs/API_Reference/Web_API_v3/Whitelabel/domains.html#Update-a-Domain-PATCH

**Comment by awwa** [comment]
Sorry. The update was insufficient. I have update the documentation about patch_wl_domain.
https://github.com/awwa/sendgrid4r/wiki/Whitelabel-Domains#patch_wl_domain
The API does not have an ability to update the domain or subdomain.

**Comment by chalmagean** [comment]
So if you want to do an update you should probably do a delete then create?

**Comment by awwa** [comment]
@chalmagean I believe it. It seems the early stage of API could have updated the domain and subdomain, but the ability has been removed now.

**Comment by chalmagean** [comment]
@awwa awesome, thanks.
