### ISSUE TITLE
campaign custom_unsubscribe_url not implemented in campaign_factory and client

### ISSUE THREAD

**Issue by johannesengl** [awwa/sendgrid4r#30]
Thanks for the great wrapper! One question. I am missing the option to set a custom unsubscribe url when creating a campaign. According to the docs it should be possible to set a suppression_group_id or a custom_unsubscribe_url on campaign creation. Will this functionality be added? BR, Johannes

**Comment by awwa** [comment]
Hi! The `custom_unsubscribe_url` and the `ip_pool` were added to the API params after I implemented this. I will add them in next version. Thanks!

**Comment by awwa** [comment]
Hi. I have released ver.1.8.0 which supports custom_unsubscribe_url and ip_pool parameters for the campaign API.

**Comment by awwa** [comment]
@johannesengl  I have updated the document.
https://github.com/awwa/sendgrid4r/wiki/Campaigns
