### ISSUE TITLE
Implement Senders Identities API

### ISSUE THREAD

**Issue by marcagas** [awwa/sendgrid4r#37]
This feature request will allow the client to create and manage sender identities.

See Reference: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/sender_identities.html

**Comment by awwa** [comment]
Thanks for mention. I have already [implemented that](https://github.com/awwa/sendgrid4r/blob/v1000/lib/sendgrid4r/rest/marketing_campaigns/senders.rb).
You can see it v1000 branch.
This will be released in next version!

**Comment by marcagas** [comment]
Hi @awwa,

Wow that's great. Thanks for this wonderful gem. When is the next release by the way?

**Comment by awwa** [comment]
Hi @marcagas ,
That have been [released](https://rubygems.org/gems/sendgrid4r/versions/1.10.0).
I want to hear your feedback!
