### ISSUE TITLE
Upgrade to SendGrid v3 Web API

### ISSUE THREAD

**Issue by thinkingserious** [awwa/sendgrid4r#47]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

**Comment by awwa** [comment]
@thinkingserious , Thanks for the notification!
Actually, sendgrid4r originally has supported [SendGrid v3 Mail Send API](https://github.com/awwa/sendgrid4r/blob/master/lib/sendgrid4r/rest/mail/mail.rb).

But I think sendgrid4r finally tends to the end of life when the sendgrid-ruby (which you made) includes enough helpers. The sendgrid-ruby's fluent interface is SO COOL.

**Comment by thinkingserious** [comment]
Thanks @awwa!

We are looking forward to implementing the rest of the helpers :)

If there are any that you would like to see prioritized, please make your voice heard by either opening an issue or commenting/thumbs up on an existing one.
